В ходе выполнения программы иногда возникают нештатные ситуации, которые называются исключениями (исключительными ситуациями). Некоторые из них программист может предусмотреть, например деление на ноль, отсутствие файла на диске, а другие предусмотреть сложнее. Большинство языков программирования предоставляют средства для обработки исключительных ситуаций.

Генерация исключения
- `throw выражение генерации исключения;`

Контролируемый блок
- `try { … };`

Обработка исключения
- `catch (тип исключения) { операторы };`

Блок после `try` позволяет выделить в любом месте программы код, который мы хотим проконтролировать. Внутри этого кода могут находится операторы вызова функций, которые генерируют исключения, а может в явном виде выполняться оператор `throw`. Когда выполняется такой оператор с помощью выражения после `throw` формируется специальный объект, называемый исключением. После формирования этого объекта выполнение дальнейшего кода после throw прерывается и управление передаётся сразу за пределы контролируемого блока `try`, где должен находится хотя бы один обработчик исключений `catch`.

Исключения могут быть разных типов. В этом случае возможны несколько обработчиков исключений catch. При этом последним можно поместить обработчик в списке параметров которого три точки. Он вызовется во всех случаях когда исключение не подойдёт под тип ни одного предыдущего обработчика и выполнит всю работу.

Типы исключений
- exception
	- bad_alloc
	- bad_rast
	- bad_typeid
	- logic_error
		- domain_error
		- invalid_argument
		- lendht_error
		- out_of_range
- ios_basic_error
- runtime_error
	- range_error
	- overflow_error
	- underflow_error
- bad_exception